{% set version = "1.10.3" %}

package:
  name: wradlib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wradlib/wradlib-{{ version }}.tar.gz
  sha256: 05331be2c4ec8b8cad41b15430513a6c70c1e33d6f4fa6b29c623b707d7ae104

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3
    - pip
    - semver
  run:
    - python >=3
    - deprecation
    - numpy
    - scipy
    - matplotlib-base
    - h5py
    - h5netcdf
    - netcdf4
    - gdal
    - xarray
    - cartopy
    - semver
    - xmltodict
    - requests

test:
  imports:
    - wradlib  # [not osx]
  commands:
    # hack to get macosx matplotlib running
    # see https://github.com/conda-forge/wradlib-feedstock/pull/20
    - python -c "import matplotlib as mpl; mpl.use('Agg'); import wradlib"  # [osx]

about:
  home: http://wradlib.org/
  license: MIT
  license_file: LICENSE.txt
  summary: Open Source Library for Weather Radar Data Processing

extra:
  recipe-maintainers:
    - kmuehlbauer
