{% set version = "2.0.0" %}

package:
  name: wradlib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wradlib/wradlib-{{ version }}.tar.gz
  sha256: 69cc8cafa188db61236fdaf19d2eb1f52c073fc8fc164fe51517e87a6162415a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3
    - pip
    - setuptools_scm
  run:
    - python >=3
    - deprecation
    - numpy
    - scipy
    - matplotlib-base
    - h5py
    - h5netcdf
    - netcdf4
    - gdal
    - xarray
    - cartopy
    - packaging
    - xmltodict
    - requests
    - xradar >=0.0.13

test:
  imports:
    - wradlib  # [not osx]
  commands:
    # hack to get macosx matplotlib running
    # see https://github.com/conda-forge/wradlib-feedstock/pull/20
    - python -c "import matplotlib as mpl; mpl.use('Agg'); import wradlib"  # [osx]

about:
  home: http://wradlib.org/
  license: MIT
  license_file: LICENSE.txt
  summary: Open Source Library for Weather Radar Data Processing

extra:
  recipe-maintainers:
    - kmuehlbauer
