{% set version = "2.3.0" %}

package:
  name: wradlib
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/w/wradlib/wradlib-{{ version }}.tar.gz
  sha256: c609266edb7beae4ef7d315b119863bf66d94dce2533f62a321d7307773a5797

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3
    - pip
    - hatchling
    - hatch-vcs
    - hatch-fancy-pypi-readme
    - hatch-requirements-txt
  run:
    - python >=3
    - deprecation
    - numpy
    - scipy
    - matplotlib-base
    - h5py
    - h5netcdf
    - netcdf4
    - gdal
    - xarray <=2024.9.0
    - cartopy
    - packaging
    - pyproj
    - xmltodict
    - requests
    - xradar >=0.4.0,<=0.7.0

test:
  imports:
    - wradlib  # [not osx]
  commands:
    # hack to get macosx matplotlib running
    # see https://github.com/conda-forge/wradlib-feedstock/pull/20
    - python -c "import matplotlib as mpl; mpl.use('Agg'); import wradlib"  # [osx]

about:
  home: http://wradlib.org/
  license: MIT
  license_file: LICENSE.txt
  summary: Open Source Library for Weather Radar Data Processing

extra:
  recipe-maintainers:
    - kmuehlbauer
