{% set version = "0.8.0" %}

package:
    name: wradlib
    version: {{ version }}

source:
    fn: wradlib-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/w/wradlib/wradlib-{{ version }}.tar.gz
    md5: 3ed24ca856a707757148a9ee298feb0c

build:
    number: 2
    script: python setup.py install

requirements:
    build:
        - python
        - numpy
        - scipy <0.18
        - matplotlib
        - h5py
        - netcdf4
        - gdal 2.1.*
    run:
        - python
        - numpy
        - scipy <0.18
        - matplotlib
        - h5py
        - netcdf4
        - gdal 2.1.*

test:
    imports:
        - wradlib

about:
    home: http://wradlib.org/
    license: MIT
    summary: "Open Source Library for Weather Radar Data Processing"

extra:
    recipe-maintainers:
        - jjhelmus
        - kmuehlbauer
