{% set version = "2.0.3" %}

package:
  name: wradlib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wradlib/wradlib-{{ version }}.tar.gz
  sha256: 0d5448a1dd0e030bdd36f7bbc69fa50aee7fb74dbc7b6407d2dc52d18ea40c49

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3
    - pip
    - hatchling
    - hatch-vcs
    - hatch-fancy-pypi-readme
    - hatch-requirements-txt
  run:
    - python >=3
    - deprecation
    - numpy
    - scipy
    - matplotlib-base
    - h5py
    - h5netcdf
    - netcdf4
    - gdal
    - xarray
    - cartopy
    - packaging
    - pyproj
    - xmltodict
    - requests
    - xradar >=0.4.0

test:
  imports:
    - wradlib  # [not osx]
  commands:
    # hack to get macosx matplotlib running
    # see https://github.com/conda-forge/wradlib-feedstock/pull/20
    - python -c "import matplotlib as mpl; mpl.use('Agg'); import wradlib"  # [osx]

about:
  home: http://wradlib.org/
  license: MIT
  license_file: LICENSE.txt
  summary: Open Source Library for Weather Radar Data Processing

extra:
  recipe-maintainers:
    - kmuehlbauer
