{% set version = "1.4.2" %}

package:
  name: wradlib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wradlib/wradlib-{{ version }}.tar.gz
  sha256: 9a8efaed437b341858f1ff73fd5dc776703ce8acb8b77dd583329bc7d32d4db0

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3
    - pip
    - semver
  run:
    - python >=3
    - deprecation
    - numpy
    - scipy
    - matplotlib
    - h5py
    - netcdf4
    - gdal
    - xarray
    - cartopy
    - semver
    - xmltodict

test:
  imports:
    - wradlib  # [not osx]
  commands:
    # hack to get macosx matplotlib running
    # see https://github.com/conda-forge/wradlib-feedstock/pull/20
    - python -c "import matplotlib as mpl; mpl.use('Agg'); import wradlib"  # [osx]

about:
  home: http://wradlib.org/
  license: MIT
  license_file: LICENSE.txt
  summary: "Open Source Library for Weather Radar Data Processing"

extra:
  recipe-maintainers:
    - jjhelmus
    - kmuehlbauer
