{% set version = "0.8.0" %}

package:
    name: wradlib
    version: {{ version }}

source:
    fn: wradlib-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/w/wradlib/wradlib-{{ version }}.tar.gz
    sha256: 04560b176156219eb6656039ebd938d95294e94cbb3f89a9211a7e1fb20e459a
    patches:
        # Patch already upstream and will be in the next version.
        - latest_scipy_dp.patch
        - latest_scipy_utils.patch

build:
    number: 2
    script: python setup.py install

requirements:
    build:
        - python
        - numpy
        - scipy
        - matplotlib
        - h5py
        - netcdf4
        - gdal 2.1.*
    run:
        - python
        - numpy
        - scipy
        - matplotlib
        - h5py
        - netcdf4
        - gdal 2.1.*

test:
    imports:
        - wradlib

about:
    home: http://wradlib.org/
    license: MIT
    summary: "Open Source Library for Weather Radar Data Processing"

extra:
    recipe-maintainers:
        - jjhelmus
        - kmuehlbauer
