{% set version = "0.9.0" %}

package:
    name: wradlib
    version: {{ version }}

source:
    fn: wradlib-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/w/wradlib/wradlib-{{ version }}.tar.gz
    sha256: 2d8b1c2871bd038c84f12bfc55b3e02a8fd5285666f8180cc641f94a20005937

build:
    number: 0
    script: python setup.py install

requirements:
    build:
        - python
        - numpy
        - scipy
        - matplotlib
        - h5py
        - netcdf4
        - gdal 2.1.*
    run:
        - python
        - numpy
        - scipy
        - matplotlib
        - h5py
        - netcdf4
        - gdal 2.1.*

test:
    imports:
        - wradlib

about:
    home: http://wradlib.org/
    license: MIT
    summary: "Open Source Library for Weather Radar Data Processing"

extra:
    recipe-maintainers:
        - jjhelmus
        - kmuehlbauer
