travis:
  secure:
    BINSTAR_TOKEN: sxKmhpf+esBQG1U8Spa+LfdLMk/pvu56wFILy8+EmQjR2fKWxhviiZPe/ZYEEjvH0d9xRW5SFzgesGnVf10pSVbPfVbEtdK7LnH4vyx9ualbsyyLHDjxGCEmuCGS2eTxIaYN5rCRZ/OEibnSBNk72etFcldun44jfJC4xAigrxsWfq82R1eQ5d4q+kbryHQY4BWhXBzVEvT0mD8hlhPJKk7sfkqEinL1nDQrxRD+zbVxxPhoxDWKUguvxSYMhEocWEruRMf1EH1/jPrbjSA11aaIjA/jZowKONVHRAQOFlygIMgg3q2HSEZ7Hn/7XHL6dUnWI40Fdpvh3WZHoUKvornVG0/x13MD9bCgO9uSERlvgIAiXQgFxwTajHOX2DiKE/BA4bDU424W58/JxMk+sGyMgY1NUjo1fwHSps+l1VGMG5KxvBHyPsq3AfZ/bWvhMZbr9bbotBjODWBs9ste3J/eRhyfwCBeLfa+8pg8hhEp9R/6bNhHYIbBYv8TL82X+P0idDqhP9AdQDfMTJTu+VBaDKJB8EYMzcPkHj9AmUbOGvjsZBM+nBQ5bbqNleJ13OxQKuvG4rZeQ+tvwwTVrJH2ZIPmtC1WAENL0IT9tjDPjPOubwgw+aTZTHseWVzGr+EDYBAqoY1kXeiw8Md83lu0A9CYxEQdr5kevB/yQRw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
