travis:
  secure:
    BINSTAR_TOKEN: EUP8SNTbO7tZGN4Nr5es2xatfe8vi5u01IUE8BNhytDSV7o65EE+myTgWK/nmFPRXQtKQcHopd037W/h3UabQxaW4krMO165+HdFbo1Vss0E9mpF3lBS98raS5ogZJOxIn3THEJYCN+8rTpNBIvBkx6l2NYRfhy17tE+JPJZpdsPuewYqr0+mI9LzC91dr4r3YzxnWUYcMqw5HJNoD2TotqNRkBkht11U8ZCQwZ9KuE4MSz1A07ZAbIEfGzTzmKhkspDxm65/lbv9bI2i9YV73KjChV7rNe7ficf1qIJvliC3zR4qvz1Zcd1NznyNOR5VzNv8z2fhFP7BB41GOupWbjmCvSqQPahEQwiuO4dyAh06ERShG0RI8Ht9hLm49IFhpWJW6TTwnPgDZVR30NvNY2cO6pW5mSOI2Nw+2C5X7LrvGrrH+1XdYP7X/vnTJ+97mhBGiDCymIyclbttF1T8lQmFHq2OsCl/Qpe0rggEepGSGkHyYKUo2qVnjnp+DsG9x8DjvnYtx5Fd+y/9gKDQBaGDZUG+SSvlED/wSFUaopD3hUMan7C9s0M8aBFVr0yQ3CvB0pdnVrjE8wlzzhwSzt/2TfW804VGPuvryXKFfn1dCYJ+BMxG2fgRrhgZx5w5KARbOLUIVHVMyyH4xkLbZ32vZAfI3LkN5CjGWvXbNM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
